apiVersion: v1
kind: Service
metadata:
  name: timecard-storybook
  labels:
    app: timecard-storybook
    service: timecard-storybook
    group: nara-drama
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: timecard-storybook
    group: nara-drama
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: timecard-storybook
spec:
  hosts:
    - "*"
  gateways:
    - nara-gateway
  http:
    - match:
        - uri:
            prefix: /timecard-storybook/
      route:
        - destination:
            host: timecard-storybook
            port:
              number: 80
